substitutions:
  device_name: "esp32-riser_v1.1_w_arduino"
  friendly_name: "ESP32 Riser v1.1 w Arduino"

esphome:
  name: "${device_name}"

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

light:
  - platform: status_led
    name: "${friendly_name} Status LED"
    id: blue_led
    disabled_by_default: true
    pin:
      inverted: true
      number: GPIO2

api: ## Add your encryption key

ota: ## Add your encryption key

web_server:
  port: 80

esp32_improv:
  authorizer: none

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:
    
